import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'primary': '#b90905',
        'primary-dim': '#a40001',
        'primary-fixed': '#ff7764',
        'primary-fixed-dim': '#ff5b48',
        'primary-container': '#ff7764',
        'on-primary': '#ffefed',
        'on-primary-fixed': '#000000',
        'on-primary-fixed-variant': '#610000',
        'on-primary-container': '#4f0000',
        'inverse-primary': '#ff5541',
        'secondary': '#745700',
        'secondary-dim': '#654c00',
        'secondary-fixed': '#ffca42',
        'secondary-fixed-dim': '#f2bc1e',
        'secondary-container': '#ffca42',
        'on-secondary': '#fff1d9',
        'on-secondary-fixed': '#433200',
        'on-secondary-fixed-variant': '#664d00',
        'on-secondary-container': '#5b4400',
        'tertiary': '#006a2f',
        'tertiary-dim': '#005d28',
        'tertiary-fixed': '#8ffda5',
        'tertiary-fixed-dim': '#80ee98',
        'tertiary-container': '#8ffda5',
        'on-tertiary': '#ceffd1',
        'on-tertiary-fixed': '#004c20',
        'on-tertiary-fixed-variant': '#006c30',
        'on-tertiary-container': '#00612b',
        'surface': '#fff4f4',
        'surface-dim': '#ffc6ca',
        'surface-bright': '#fff4f4',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#ffeced',
        'surface-container': '#ffe1e2',
        'surface-container-high': '#ffdadb',
        'surface-container-highest': '#ffd2d4',
        'surface-variant': '#ffd2d4',
        'surface-tint': '#b90905',
        'on-surface': '#4d2126',
        'on-surface-variant': '#824c51',
        'inverse-surface': '#240307',
        'inverse-on-surface': '#cc8c91',
        'background': '#fff4f4',
        'on-background': '#4d2126',
        'outline': '#a1676c',
        'outline-variant': '#de9ca1',
        'error': '#b41340',
        'error-dim': '#a70138',
        'error-container': '#f74b6d',
        'on-error': '#ffefef',
        'on-error-container': '#510017',
      },
      borderRadius: {
        DEFAULT: '1rem',
        'sm': '0.5rem',
        'md': '1rem',
        'lg': '2rem',
        'xl': '3rem',
        'full': '9999px',
      },
      fontFamily: {
        headline: ['var(--font-plus-jakarta)', 'Plus Jakarta Sans', 'sans-serif'],
        body: ['var(--font-be-vietnam)', 'Be Vietnam Pro', 'sans-serif'],
        label: ['var(--font-plus-jakarta)', 'Plus Jakarta Sans', 'sans-serif'],
      },
      boxShadow: {
        'ambient': '0 20px 40px rgba(77, 33, 38, 0.08)',
        'ambient-lg': '0 24px 48px rgba(77, 33, 38, 0.12)',
        'primary-glow': '0 8px 24px rgba(185, 9, 5, 0.40)',
      },
      animation: {
        'pulse-ring': 'pulse-ring 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'fade-in': 'fade-in 0.3s ease-out',
        'slide-up': 'slide-up 0.3s ease-out',
      },
      keyframes: {
        'pulse-ring': {
          '0%, 100%': { opacity: '0.5', transform: 'scale(1)' },
          '50%': { opacity: '0.2', transform: 'scale(1.08)' },
        },
        'fade-in': {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        'slide-up': {
          from: { opacity: '0', transform: 'translateY(16px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
}

export default config
